---
title: "VectorByte Methods Training: Dengue Forecasting Challenge"
author:
  - name: 
      given: Alicia
      family: Arneson
    affiliation: Virginia Tech and VectorByte
  - name: 
      given: Leah R.
      family: Johnson
    url: https://lrjohnson0.github.io/QEDLab/leahJ.html
    affiliation: Virginia Tech and VectorByte
citation: true
date: 2025-06-03
date-format: long
format:
  html:
    toc: true
    toc-location: left
    html-math-method: katex
    css: styles.css
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

set.seed(123)
```

# Overview

Using the skills you have gained in this year's training, we are going to build some real forecasting models! We will focus on one part of a larger forecasting challenge called the Infodengue-Mosqlimate Dengue Challenge (IMDC). It aims to help make improved predictions of weekly dengue cases (incidence) in Brazil.

The IMDC involves three validation tests and one forecasting task, each focusing on predicting weekly dengue cases by state (UF) for specific epidemiological seasons:

*Validation Test 1:* Predict cases for the 2022–2023 season using data from 2010 to mid-2022.

*Validation Test 2:* Predict cases for the 2023–2024 season using data up to mid-2023.

*Validation Test 3:* Predict cases for the 2024–2025 season using data up to mid-2024.

*Forecast Task:* Predict cases for the 2025–2026 season using data up to mid-2025.

Each model must provide median estimates along with 50%, 80%, 90%, and 95% predictive intervals for all 27 Brazilian federative units.

See this link for the full challenge details: https://sprint.mosqlimate.org/2025/

For time's sake, we will focus on making forecasts for just one of the 27 states, and we will work with validation test 3


# Instructions

## Easier version
1 state, covariates already attached, just validation test 3
Using the 

## Harder version
10 states, covariates available but not attached, all validation tests and forecasting task

