---
title: "VectorByte Training Materials 2025"
format:
  html:
    toc: true
    toc-location: left
    html-math-method: katex
    css: styles.css
---

# Pre-work and set-up

## Hardware and Software

- We will be using [`R`](https://cran.r-project.org/) for all data manipulation and analyses/model fitting. Any operating system (Windows, Mac, Linux) will do, as long as you have `R` (version 3.6 or higher) installed.

- You may use any IDE/ GUI for `R` (VScode, RStudio, Emacs, etc). For most people, [`RStudio`](https://www.rstudio.com/) is a good option. Whichever one you decide to use, please make sure it is installed and tested before the workshop.

- We will also be using Slack for additional support during the training. Accepted students will receive an e-mail with joining information. We will have a channel on Slack dedicated to software/hardware issues and troubleshooting. 

- We also host all materials on [GitHub](https://github.com/), and we recommend that all students have a GitHub account. 

## Pre-requisites

We are assuming familiarity with `R` basics as well as at least introductory statistics, including up through simple linear regression. If you would like materials to review, we recommend that you do the following:

***Review of `R`***

1.  Go to [The Multilingual Quantitative Biologist](https://mhasoba.github.io/TheMulQuaBio/intro.html), and read+work through the [Biological Computing in R Chapter](https://mhasoba.github.io/TheMulQuaBio/notebooks/07-R.html).

2.  In addition / alternatively to pre-work element (1), here are some resources for brushing up on R [at the end of the Intro R Chapter you can try](https://mhasoba.github.io/TheMulQuaBio/notebooks/07-R.html#readings-and-resources). There are many more resources online (e.g., [this](https://www.codecademy.com/learn/learn-r) and [this](https://www.dataquest.io/blog/learn-r-for-data-science/) ) -- pick something that suits your learning style.

<br>

***Review of statistics***

1.  Review background on [introductory probability and statistics](Stats_review.qmd) ([solutions to exercises](Stats_review_soln.qmd)). You can also use the resources on [The Multilingual Quantitative Biologist - Basic Data Analyses and Statistics](https://mhasoba.github.io/TheMulQuaBio/Stats-Intro.html) through into linear models.

2.  Review the conceptual basics of [Simple Linear Regression](VB_RegRev.qmd). We'll refresh fitting linear models in R as well as transformations and diagnostic plots during the workshop.

<br> <br>

# Live Workshop Materials

## Introduction to the Workshop

-   [Lecture Slides](VB_IntroTimeDepData.qmd)

<br> <br>

## Regression in R Refresher (Transformations and Diagnostics)

-   [Lecture Slides](VB_RegDiagTrans.qmd)
-   [Practical](VB_RegDiagTrans_practical.qmd)
-   Dataset: [transforms.csv](/data/transforms.csv)

<br> <br>

## Introduction to the VecDyn database

-   [The VecDyn website](https://vectorbyte.crc.nd.edu/vecdyn-datasets)
-   [About the VecDyn API](https://www.vectorbyte.org/blog/vecdyn-api)
-  [Intro to VecDyn (slides)](
https://docs.google.com/presentation/d/1GZuAR8zFRFJaR1QConiNHG5v71W4psAd/edit?usp=sharing&ouid=103950001421882927979&rtpof=true&sd=true)
- [VecDyn Files for Uploading](https://drive.google.com/drive/folders/1BBK3zWEm3uuKDttXJquDKXDwXTodh8XB?usp=sharing)

<br> <br>

## Time dependent regression analysis

-   [Lecture Slides](VB_TimeDepData.qmd)
-   [Practical](VB_TimeDepData_practical.qmd)
-   Dataset: [Walton Co, FL Mosquito data](/data/Culex_erraticus_walton_covariates_aggregated.csv)

<br> <br>


## Introduction to climate and weather data for time dependent analyses

- [Guided Practice](VByteWkshp25_Climate_SJR.qmd)
- dataset: [NEON_tickplots_13sites_utf8.csv](data/NEON_tickplots_13sites_utf8.csv)

<br><br>


## Basics of Forecasting Time Series using `R`

-   [Lecture Slides](VB_TimeSeries.qmd)
-   [Practical](VB_TimeSeriesForecastingPractical.qmd)
-   Dataset: [NEONphenologyClean.csv](data/NEONphenologyClean.csv)


<br> <br>


## Gaussian Process models (GPs) for Time Dependent Data

-   [Lecture Slides](VB_GP_slides.qmd)
-   [Lecture Notes -- coming soon]()
-   [Practical](VB_GP_Practical.qmd)

<br> <br>

## Dengue Forecasting Challenge

- [Description](DengueForecastingChallenge.qmd)
- dataset: [dengueForecasting.csv](data/dengueForecasting.csv)
- helper code: [dengueForecastingChallenge.R](dengueForecastingChallenge.R)

<br>
<br>

